# Generated by Django 5.1.2 on 2024-10-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unisave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_income',
            new_name='total_income',
        ),
    ]
